apiVersion: apps/v1
kind: Deployment
metadata:
  name: videos
spec:
  selector:
    matchLabels:
      app: videos
  template:
    metadata:
      labels:
        app: videos
    spec:
      containers:
        - name: golangvideos
          image: golangapps.azurecr.io/golangvideos:v4
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: dockerlogin

---
apiVersion: v1
kind: Service
metadata:
  name: videos-service
spec:
  selector:
    app: videos
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP

      
